### ISSUE TITLE
cant find module glue

### ISSUE THREAD

**Issue by schwittlick** [k0a1a/hotglue2#12]
hey there,

this is probably easy, so hopefully you have a short tip for me why i am running into this error on my fresh install

```
2017-10-31 14:55:04    XX.XX.XX.XX  12447   error   modules: cannot find required module glue, make sure it is installed in the program directory
```

thanks already, this looks interesting. cant wait to check it out a bit myself.

yours,
marcel

**Comment by dereckson** [comment]
The error is thrown by load_modules() in modules.inc.php

It means the working directory is NOT the hotglue2 directory, ie it's not the directory where you've module_glue.inc.php.

How do you configure your application? ie:
  1. do you embed Hotglue in another app? do you use it directly?
  2. with Apache? with nginx? 
  3. what's your server/VirtualHost block configuration?

For your assessment, it's as easy as fixing the working directory to match the hotglue2 directory, which could be damned complicated in some scenarii.

**Comment by schwittlick** [comment]
hmm, i wonder why.. but to answer your questions:

1. i am only using hotglue, directly.
2. with apache2
3. while trying to figure this out, i actually came across the problem. the ownership of the folder where hotglue was contained in was skewed.

thanks a lot \o/

**Comment by dereckson** [comment]
Ah yes, to include the file, it needs two permissions:
- the execution bit (x, or in chmod notation 1, so 1, 5 or 7) on the directory to be able to browse it
- the reading bit (r, or in chmod notation 4, so 4, 5, 6 or 7) on the file

If not, it can't include the file.

**Comment by k0a1a** [comment]
glad to see the issue being resolved, tnx @dereckson for your input
