### ISSUE TITLE
Basic authentication - HTTP/1.1 401 Unauthorized

### ISSUE THREAD

**Issue by markphd** [k0a1a/hotglue2#2]
Installed Hotglue in a shared hosting, set authentication to basic but when creating new page, the login prompt does not accept the correct login, it keeps asking for the username and password.

**Comment by k0a1a** [comment]
hi,

it is a known bug on hosts running PHP via fCGI. the solutions might differ depending on each particular case. 
does setting AUTH to 'none' let you enter editing mode?
could you supply output of phpinfo() ?

best,

On March 29, 2014 5:40:37 AM CET, "Mark Philip D." notifications@github.com wrote:

> Installed Hotglue in a shared hosting, set authentication to basic but
> when creating new page, the login prompt does not accept the correct
> login, it keeps asking for the username and password.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/hotglue/hotglue2/issues/2

## 

sent from a black mirror device.
transmission corruptions to be expected.

**Comment by k0a1a** [comment]
see https://github.com/hotglue/hotglue2/commit/eccbc76a51c97b42ecad84cfd233d2bf0172c577

your server might be returning a string other then 'Authorization' which is thus not parsed correctly. If that's the case you might also need to check .htacess file for proper rewrite rule (apache mod_rewrite needs to be available).

On March 29, 2014 5:40:37 AM CET, "Mark Philip D." notifications@github.com wrote:

> Installed Hotglue in a shared hosting, set authentication to basic but
> when creating new page, the login prompt does not accept the correct
> login, it keeps asking for the username and password.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/hotglue/hotglue2/issues/2

## 

sent from a black mirror device.
transmission corruptions to be expected.

**Comment by markphd** [comment]
Thanks for attending to it. Used basic auth and set password in plain text in user-config.inc.php and config.inc.php - worked perfectly well.
