### ISSUE TITLE
Multi-tenancy Support for HotGlue

### ISSUE THREAD

**Issue by michaelha** [k0a1a/hotglue2#20]
To the Development team for hotglue2:
 
My name is Michael Ha from the Arts Instructional Support and Information Technology (ArtsISIT) at University of British Columbia.  Currently we are in process of implementing HotGlue as a tool that we would like to implement for a Visual Art class here at UBC. 

I would like to request additional support for the installation of hotglue2 in a Multi-tenancy/Multi-user environment.  I have reviewed the installation documentation https://github.com/k0a1a/hotglue2/blob/dev/INSTALL and was able to install an single instance of the application to a web server (the web server name is hg.arts.ubc.ca) hosted in RedHat Enterprise Linux 7.  However, we would like to utilize the tool similarly to what is offered in the hosted version of Hotglue.me, which it gives user the ability to create an user account via the registration page: https://hotglue.me/account/register and from there the user has the option to select a hotglue username and a desired subdomain for its HotGlue instance.  
 
Does hotglue2 have support the ability to install in a multi-user and multi-tenancy environment in a self-installed environment?  If I have a wildcard domain name (*.hg.arts.ubc.ca) pointing to the web server, is it possible to configure the application so it can support multi-user via a subdomain set up? For example, can we have user1.hg.arts.ubc.ca, user2.hg.arts.ubc.ca, … userN.hg.arts.ubc.ca pointing to the web server and be able to set up installation have its own?  We needed a solution for provision 90 instances. Is there Apache setting or Application configuration settings that your team can offer in order for us to achieve the desired outcome?
 
Regards,
Michael Ha
UBC ArtsISIT Development Team

**Comment by k0a1a** [comment]
Hello Michael,

the Hotglue code itself does not provide multi-domain/multi-user functionality. Hotglue.me service is deployed using a custom server configuration and user-management framework. Please email me at danja-at-hotglue.me if you are interested in further details.
