### ISSUE TITLE
talk@hotglue.org not working

### ISSUE THREAD

**Issue by hellocatfood** [k0a1a/hotglue2#5]
I tried to contact hotglue via the talk@hotglue.org address on the website and it is no longer working:

Delivery to the following recipient failed permanently:

```
 talk@hotglue.org
```

Technical details of permanent failure:
Google tried to deliver your message, but it was rejected by the server for the recipient domain hotglue.org [213.108.105.120].

The error that the other server returned was:
554 5.1.1 talk@hotglue.org: Recipient address rejected: User unknown in virtual mailbox table

**Comment by k0a1a** [comment]
we had to suspend this email address due to spam. please use help@hotglue.me
